### ISSUE TITLE
psychics 스냅샷2.0 빌드 오류

### ISSUE THREAD

**Issue by UYEOL32** [monun/psychics#17]
다른 사람꺼 빌드 해도 이렇게 뜨던데 어떻게 해야 하나요.

Execution failed for task ':psychics-core:compileKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':psychics-core:compileKotlin'
   > Could not resolve all files for configuration ':psychics-core:compileClasspath'.
      > Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT.
        Required by:
            project :psychics-core
         > No matching variant of io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT:20210810.050951-80 was found. The consumer was configured to find an API of a library compatible with Java 14, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT declares an API of a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 14
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
             - Variant 'javadocElements' capability io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT declares a runtime of a component, and its dependencies declared externally:
                 - Incompatible because this component declares documentation and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about its target Java version (required compatibility with Java 14)
                     - Doesn't say anything about its elements (required them preferably in the form of class files)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
             - Variant 'runtimeElements' capability io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 14
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
             - Variant 'sourcesElements' capability io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT declares a runtime of a component, and its dependencies declared externally:
                 - Incompatible because this component declares documentation and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about its target Java version (required compatibility with Java 14)
                     - Doesn't say anything about its elements (required them preferably in the form of class files)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
      > Could not resolve io.github.monun:tap-api:4.1.3.
        Required by:
            project :psychics-core
         > No matching variant of io.github.monun:tap-api:4.1.3 was found. The consumer was configured to find an API of a library compatible with Java 14, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.github.monun:tap-api:4.1.3 declares an API of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 14
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
             - Variant 'runtimeElements' capability io.github.monun:tap-api:4.1.3 declares a runtime of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 14
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
      > Could not resolve io.github.monun:kommand-api:2.4.1.
        Required by:
            project :psychics-core
         > No matching variant of io.github.monun:kommand-api:2.4.1 was found. The consumer was configured to find an API of a library compatible with Java 14, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.github.monun:kommand-api:2.4.1 declares an API of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 14
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
             - Variant 'runtimeElements' capability io.github.monun:kommand-api:2.4.1 declares a runtime of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 14
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
      > Could not resolve io.github.monun:invfx-api:3.0.0.
        Required by:
            project :psychics-core
         > No matching variant of io.github.monun:invfx-api:3.0.0 was found. The consumer was configured to find an API of a library compatible with Java 14, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.github.monun:invfx-api:3.0.0 declares an API of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 14
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
             - Variant 'runtimeElements' capability io.github.monun:invfx-api:3.0.0 declares a runtime of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 14
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by Hinoto04** [comment]
자바 버전이 16이어야 합니다. 프로젝트 자바 버전을 16으로 바꿔주세요

**Comment by qogusdn1017** [comment]
이슈 닫아주세요.

**Comment by heisenberg-cat** [comment]
이슈 닫아주세요
