### ISSUE TITLE
능력을 불러오지 못하는 오류

### ISSUE THREAD

**Issue by BlueRing1017** [monun/psychics#23]
클래스 경로를 변경하지 않고, com.github.noonmaru.psychic.ability.능력이름 으로 하면 오류가 생기지 않으나, 이곳을 위키대로 변경하면, 불러오지 못하는 것 같습니다.

**Comment by dytroInc** [comment]
위키는 예전 버전이라, 이번 새로운 능력자를 수정하실 거면 코드를 좀 더 분석하거나 위키 업데이트를 기다리세요.

혹시 빠르게 이번에 새로 나온 능력자 해보고 싶나요.
