### ISSUE TITLE
 Could not resolve 오류

### ISSUE THREAD

**Issue by abcd0912** [monun/psychics#24]
아래 오류 메세지들을 해결하는 법 아시는 분 계신가요?
Could not resolve io.github.monun:tap-api:4.1.5.
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT.
Could not resolve io.github.monun:kommand-api:2.6.1.
Could not resolve io.github.monun:invfx-api:3.0.0.

**Comment by qogusdn1017** [comment]
Java 16으로 업데이트

이슈 닫아주세요.
