### ISSUE TITLE
능력 yml 수정이 안됩니다

### ISSUE THREAD

**Issue by sgkill6** [monun/psychics#28]
group: io.github.monun
name: storm-breaker
version: 2.0.0-SNAPSHOT
main: io.github.monun.psychics.ability.stormbreaker.AbilityStormBreaker
author: Monun
display-name: storm
health-bonus: 10.0
health-regen-per-second: 10.0
mana: 300.0
mana-regen-per-second: 10.0
mana-color: BLUE
description:
- '{"italic":false,"color":"white","text":"description"}'
abilities: {}

descrption abilities이 수정이 안됩니다 제가 뭘 잘못 만졌나요

**Comment by dytroInc** [comment]
plugin.yml을 건드리면 안 됩니다.

**Comment by dytroInc** [comment]
능력은 따로 plugins/Psychics/psychics를 따로 수정해야합니다.

**Comment by sgkill6** [comment]
psychics 파일에 있는 yml을 수정한겁니다

**Comment by dytroInc** [comment]
근데 보니까 plugin.yml 형식이랑 비슷한 걸로 보이는데

```yml
abilities:
  (능력 표시명):
    ability: .(능력 아이디)
```
형식으로 쓰고 /psy reload 하면, 자동으로 형식 써주니까 그걸 보세요.

**Comment by supplydeopotjelly** [comment]
> 근데 보니까 plugin.yml 형식이랑 비슷한 걸로 보이는데
> 
> ```yaml
> abilities:
>   (능력 표시명):
>     ability: .(능력 아이디)
> ```
> 
> 형식으로 쓰고 /psy reload 하면, 자동으로 형식 써주니까 그걸 사용하세요.

display-name: storm-breaker
health-bonus: 0.0
health-regen-per-second: 0.0
mana: 0.0
mana-regen-per-second: 0.0
mana-color: BLUE
description:
- '{"italic":false,"color":"white","text":"설명"}'
abilities: {}
이렇게 바뀌는데 오류가 있나요?
