### ISSUE TITLE
psychics-master 파일을 그냥 플긴 폴더에 넣는건가요?

### ISSUE THREAD

**Issue by jamI1011** [monun/psychics#29]
아님 .jar 로 이케저케 해야하나요?

**Comment by hb3810** [comment]
빌드해서 .jar 파일을 얻으셔야 되요. 빌드 방법은 유튜브에 치면 나와요.

**Comment by dytroInc** [comment]
각 submodule에서 gradlew clean paperJar 런하세요.

**Comment by supplydeopotjelly** [comment]
.유튜브에서 찾은 빌드 방법으로 해봤는데
오류: 기본 클래스 org.gradle.wrapper.GradleWrapperMain을(를) 찾거나 로드할 수 없습니다. 라고 뜨네요
뭐죠

**Comment by hb3810** [comment]
> .유튜브에서 찾은 빌드 방법으로 해봤는데
> 오류: 기본 클래스 org.gradle.wrapper.GradleWrapperMain을(를) 찾거나 로드할 수 없습니다. 라고 뜨네요
> 뭐죠

https://youtu.be/ter32OsFbvc 저는 이 영상 따라하고 성공했어요

**Comment by myoun** [comment]
그냥 인텔리제이 받고 빌드하세요
