### ISSUE TITLE
빌드 하고 나온 파일을 플러그인 폴더에 넣었는데 적용이 되지 않습니다.(페이퍼 사용합니다)

### ISSUE THREAD

**Issue by supplydeopotjelly** [monun/psychics#32]
플러그인을 빌드하니 
빌드 석세스풀이 떴습니다.
그리고 나온 파일을 페이퍼의 플러그인 폴더에 넣었습니다
그리고 동시에 월드에딧도 같이 넣었는데
월드에딧만 인식이 되네요

**Comment by sharkzhs83** [comment]
해결되셨다면 혹시 어떻게 해결하셨죠?
