### ISSUE TITLE
능력이 없는 오류

### ISSUE THREAD

**Issue by supplydeopotjelly** [monun/psychics#34]
플러그인 적용할때 오류메시지가 뜨진 않은거같은데
서버에서 psy 명령어를 치고 어태치 그리고 대상설정 한 후에 능력 이름을 적어도 적용이 되지 않습니다
그래서 서버의 플러그인 폴더에 들어가서 그 폴더 안의 physics 폴더를 살펴보았는데
어빌리티, 에스퍼, 피직스 3 폴더가 있었습니다, 어빌리티 폴더와 피직스 폴더를 살펴보니까 폴더가 비어있네요
원래 이런건가요?

**Comment by dytroInc** [comment]
기본적으로 비어있습니다. 하지만 추후 추가하는 방식이죠.

abilities엔 능력 .jar 파일을 추가하고요, psychics엔 .yml 파일을 추가합니다.

**Comment by supplydeopotjelly** [comment]
감사합니다
 
dytroInc님

**Comment by dytroInc** [comment]
close 부탁드립니다.

**Comment by qogusdn1017** [comment]
이슈 닫아주세요.
