### ISSUE TITLE
서버 1.17.1 업데이트

### ISSUE THREAD

**Issue by godlegendshot** [monun/psychics#35]
paper 1.17.1 서버 업데이트를 했는데 매직 아처, 직선 수리검, 부매랑이 고장났습니다. 어떻게 해야하나요?

**Comment by dytroInc** [comment]
저 능력들은 예전 psychics를 토대로 만든 거라서 이번 리메이크된 psychics가 지원하지 않습니다.

**Comment by godlegendshot** [comment]
그 1.0.1버전의 릴리즈 탭에 있는걸로 설치 했는데 그 부분이 예전 psychic으로 제작된건가요?

**Comment by godlegendshot** [comment]
> 정신병자들을 지원하지 못하게 되었습니다.

그 1.0.1버전의 릴리즈 탭에 있는걸로 설치 했는데 그 부분이 예전 psychic으로 제작된건가요?

> 정신병자들을 지원하지 못하게 되었습니다.

**Comment by godlegendshot** [comment]
> 저 능력들은 예전 psychics를 토대로 만든 거라서 이번 리메이크된 psychics가 지원하지 않습니다.

그 1.0.1버전의 릴리즈 탭에 있는걸로 설치 했는데 그 부분이 예전 psychic으로 제작된건가요?

**Comment by myoun** [comment]
> > 저 능력들은 예전 psychics를 토대로 만든 거라서 이번 리메이크된 psychics가 지원하지 않습니다.
> 
> 그 1.0.1버전의 릴리즈 탭에 있는걸로 설치 했는데 그 부분이 예전 psychic으로 제작된건가요?

README.md를 보시면 `현재 개발 진행중으로 배포 버전이 없습니다.` 라고 적혀 있습니다.
버전 1.0.1의 릴리즈 날짜를 보시면, 2021년 2월로, 예전 버전입니다.
