### ISSUE TITLE
어떤 yml파일을 넣어야 하는건가요

### ISSUE THREAD

**Issue by supplydeopotjelly** [monun/psychics#36]
.yml 파일을 넣어보고 서버를 실행해봤는데 능력 목록에 plugin이 뜨더군요
plugin,yml파일이 원인으로 보여서 각 능력 파일에 있는 yml을 넣어야 하는건가 했는데 그런건 못찾았습니다

**Comment by rophin** [comment]
yml 파일을 만들어야 합니다. [https://github.com/noonmaru/psychics/wiki/%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0](확인 부탁드려요.l)

**Comment by qogusdn1017** [comment]
이슈 닫아주세요.
