### ISSUE TITLE
능력이 이상하게 불러와 집니다.

### ISSUE THREAD

**Issue by supplydeopotjelly** [monun/psychics#39]
abilities:
  (이름):
    ability: .(이름)
이렇게 적어서 yml파일을 만들고 플러그인 폴더의 피직스 폴더의 피직스 폴더에 저장했습니다.
파일 이름이 stormbreaker였는데 서버를 실행하고 psy attatch @p 까지 쳐보니 자동완성으로 stormbreaker가 뜨고 명령어를 실행해보고 info를 보니 아무 설명도 나와있지 않습니다.

**Comment by dytroInc** [comment]
파일을 어떻게 했는지 보내주실 수 있나요?

**Comment by qogusdn1017** [comment]
문제 해결 되었다면 이슈 닫아주세요.
