### ISSUE TITLE
빌드버그 

### ISSUE THREAD

**Issue by minjoon1106** [monun/psychics#45]
위키따라하는데

failed
:psychics-core:compileKotlin
No matching variant of io.github.monun:invfx-api:3.0.0 was found. The consumer was configured to find an API of a library compatible with Java 13, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but: 

Execution failed for task ':psychics-core:compileKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':psychics-core:compileKotlin'
   > Could not resolve all files for configuration ':psychics-core:compileClasspath'.
      > Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT.
        Required by:
            project :psychics-core
         > No matching variant of io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT:20210818.185827-106 was found. The consumer was configured to find an API of a library compatible with Java 13, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT declares an API of a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
             - Variant 'javadocElements' capability io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT declares a runtime of a component, and its dependencies declared externally:
                 - Incompatible because this component declares documentation and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about its target Java version (required compatibility with Java 13)
                     - Doesn't say anything about its elements (required them preferably in the form of class files)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
             - Variant 'runtimeElements' capability io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
             - Variant 'sourcesElements' capability io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT declares a runtime of a component, and its dependencies declared externally:
                 - Incompatible because this component declares documentation and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about its target Java version (required compatibility with Java 13)
                     - Doesn't say anything about its elements (required them preferably in the form of class files)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
      > Could not resolve io.github.monun:tap-api:4.1.6.
        Required by:
            project :psychics-core
         > No matching variant of io.github.monun:tap-api:4.1.6 was found. The consumer was configured to find an API of a library compatible with Java 13, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.github.monun:tap-api:4.1.6 declares an API of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
             - Variant 'runtimeElements' capability io.github.monun:tap-api:4.1.6 declares a runtime of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
      > Could not resolve io.github.monun:kommand-api:2.6.4.
        Required by:
            project :psychics-core
         > No matching variant of io.github.monun:kommand-api:2.6.4 was found. The consumer was configured to find an API of a library compatible with Java 13, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.github.monun:kommand-api:2.6.4 declares an API of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
             - Variant 'runtimeElements' capability io.github.monun:kommand-api:2.6.4 declares a runtime of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
      > Could not resolve io.github.monun:invfx-api:3.0.0.
        Required by:
            project :psychics-core
         > No matching variant of io.github.monun:invfx-api:3.0.0 was found. The consumer was configured to find an API of a library compatible with Java 13, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.github.monun:invfx-api:3.0.0 declares an API of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
             - Variant 'runtimeElements' capability io.github.monun:invfx-api:3.0.0 declares a runtime of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 
라고 뜨면서 빌드가 안됩니다 무엇이 문제일까요ㅠ

**Comment by rophin** [comment]
혹시 JDK 13으로 하면 어떤 결과가 나오나요?

**Comment by minjoon1106** [comment]
Execution failed for task ':psychics-core:compileKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':psychics-core:compileKotlin'
   > Could not resolve all files for configuration ':psychics-core:compileClasspath'.
      > Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT.
        Required by:
            project :psychics-core
         > No matching variant of io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT:20210818.185827-106 was found. The consumer was configured to find an API of a library compatible with Java 13, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT declares an API of a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
             - Variant 'javadocElements' capability io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT declares a runtime of a component, and its dependencies declared externally:
                 - Incompatible because this component declares documentation and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about its target Java version (required compatibility with Java 13)
                     - Doesn't say anything about its elements (required them preferably in the form of class files)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
             - Variant 'runtimeElements' capability io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
             - Variant 'sourcesElements' capability io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT declares a runtime of a component, and its dependencies declared externally:
                 - Incompatible because this component declares documentation and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about its target Java version (required compatibility with Java 13)
                     - Doesn't say anything about its elements (required them preferably in the form of class files)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
      > Could not resolve io.github.monun:tap-api:4.1.6.
        Required by:
            project :psychics-core
         > No matching variant of io.github.monun:tap-api:4.1.6 was found. The consumer was configured to find an API of a library compatible with Java 13, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.github.monun:tap-api:4.1.6 declares an API of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
             - Variant 'runtimeElements' capability io.github.monun:tap-api:4.1.6 declares a runtime of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
      > Could not resolve io.github.monun:kommand-api:2.6.4.
        Required by:
            project :psychics-core
         > No matching variant of io.github.monun:kommand-api:2.6.4 was found. The consumer was configured to find an API of a library compatible with Java 13, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.github.monun:kommand-api:2.6.4 declares an API of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
             - Variant 'runtimeElements' capability io.github.monun:kommand-api:2.6.4 declares a runtime of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
      > Could not resolve io.github.monun:invfx-api:3.0.0.
        Required by:
            project :psychics-core
         > No matching variant of io.github.monun:invfx-api:3.0.0 was found. The consumer was configured to find an API of a library compatible with Java 13, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.github.monun:invfx-api:3.0.0 declares an API of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
             - Variant 'runtimeElements' capability io.github.monun:invfx-api:3.0.0 declares a runtime of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 13
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

라고 뜨네요 ㅠ

**Comment by minjoon1106** [comment]
finished
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:kommand-api:2.6.4
Could not resolve io.github.monun:invfx-api:3.0.0
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:kommand-api:2.6.4
Could not resolve io.github.monun:invfx-api:3.0.0
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
라고 뜨네요
