### ISSUE TITLE
의존성 플러그인

### ISSUE THREAD

**Issue by ada2121** [monun/psychics#46]
빌드하는데 필요한 의존성 플러그인에는 무엇이 있나요?

**Comment by rophin** [comment]
[깃허브위키](https://github.com/monun/psychics/wiki/%EC%9D%98%EC%A1%B4%EC%84%B1-%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8-%EC%84%A4%EC%B9%98)에 있습니다. 이슈 Close 바랍니다.

**Comment by ada2121** [comment]
invfx 빌드 오류에 대해 말해주실수 있나요?
> Task :invfx-api:signDokkaJar FAILED

FAILURE: Build failed with an exception.
빌드를 하는데 다른건 되지만 이 플긴은 이런 오류로 인해 안 됩니다
