### ISSUE TITLE
빌드하던중

### ISSUE THREAD

**Issue by minjoon1106** [monun/psychics#47]
finished
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:kommand-api:2.6.4
Could not resolve io.github.monun:invfx-api:3.0.0
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:kommand-api:2.6.4
Could not resolve io.github.monun:invfx-api:3.0.0
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.github.monun:tap-api:4.1.6
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve io.github.monun:tap-api:4.1.6
라고 뜨면서 빌드가 안되네요 ㅠㅠ

**Comment by rophin** [comment]
#45 와 같은 문제네요.

**Comment by qogusdn1017** [comment]
이슈 닫아주세요.
