### ISSUE TITLE
로딩오류

### ISSUE THREAD

**Issue by sharkzhs83** [monun/psychics#49]
일단 능력이 실행 되는지만 테스트 할려고 했는데
서버에서 인식을 못하네요

![image](https://user-images.githubusercontent.com/88832594/130609460-0d33fdd4-0932-4a63-b49d-08c782af4b33.png)

![image](https://user-images.githubusercontent.com/88832594/130609533-390cab48-afb3-4e3b-94c4-6f7dfd0cfb2d.png)

**Comment by dytroInc** [comment]
클래스명을 AbilityWizard로 해주셔야합니다.

**Comment by ada2121** [comment]
> 클래스명을 AbilityWizard로 해주셔야합니다.

혹시 님 cannot resolve 오류를 어떻게 고치는지 아나요?

**Comment by sharkzhs83** [comment]
> 클래스명을 AbilityWizard로 해주셔야합니다.

앞에 Ability를 붙여 봤지만 똑같네요

혹시 자신의 능력 빌드 파일을 어떻게 얻으시나요?

**Comment by dytroInc** [comment]
> > 클래스명을 AbilityWizard로 해주셔야합니다.
> 
> 앞에 Ability를 붙여 봤지만 똑같네요
> 
> 혹시 자신의 능력 빌드 파일을 어떻게 얻으시나요?

psychics-abilities 서브모듈에서 build하시면 되는데, 개발하는 입장이면 gradlew clean paperJar로 편하게 할 수 있습니다.

**Comment by qogusdn1017** [comment]
혹여나 해결되었다면 이슈 닫아주세요.
