### ISSUE TITLE
빌드 오류

### ISSUE THREAD

**Issue by ada2121** [monun/psychics#50]
의존성 플러그인들을 빌드하던 중 
invfx 빌드가 발생했습니다.

Task :invfx-api:signDokkaJar FAILED

FAILURE: Build failed with an exception.
빌드를 하는데 다른건 되지만 이 플긴은 이런 오류로 인해 안 됩니다

**Comment by myoun** [comment]
왜 dokkaJar로 올릴려 하시나요?

**Comment by ada2121** [comment]
> 왜 dokkaJar로 올릴려 하시나요?

에? 저 그냥 ./gradlew build로 빌드한건데 이렇게 하는게 아닌가요?

**Comment by ada2121** [comment]
> 왜 dokkaJar로 올릴려 하시나요?

아 ./gradlew clean jar 로 빌드를 해봤는데 성공했지만 플러그인으로써의 역할을 못합니다. 애초에 plugin.yml이 없다네요.

**Comment by dytroInc** [comment]
psychics-abilities, psychics-core 둘 다 gradlew clean paperJar 시도해보실래요?

**Comment by ada2121** [comment]
> psychics-abilities, psychics-core 둘 다 gradlew clean paperJar 시도해보실래요?
그게 무슨말인가요? 빌드는 그냥 전체로 하는거아닌가요?
빌드를 인텔리제이로해야하나요?

**Comment by ada2121** [comment]
> psychics-abilities, psychics-core 둘 다 gradlew clean paperJar 시도해보실래요?

어 빌드하는데 invfx플러그인 필요없나요?
core에 있는 psychics를 넣으니 되는군요
