### ISSUE TITLE
능력 빌드 오류

### ISSUE THREAD

**Issue by ada2121** [monun/psychics#52]
> Task :prepareKotlinBuildScriptModel UP-TO-DATE
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.github.monun:kommand-api:2.6.4
Could not resolve: io.github.monun:invfx-api:3.0.0
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.github.monun:kommand-api:2.6.4
Could not resolve: io.github.monun:invfx-api:3.0.0
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.6

BUILD SUCCESSFUL in 2s
이게 대체 무슨 오류인가요?
tpa, kommand, invfx, paper을 해결할 수 없다는게 뭐죠?

**Comment by qogusdn1017** [comment]
Java 16으로 업그레이드 해보시길 바랍니다.

해결되셨다면 이슈 닫아주세요.

**Comment by ada2121** [comment]
> Java 16으로 업그레이드 해보시길 바랍니다.
> 
> 해결되셨다면 이슈 닫아주세요.

와.. 3개월 동안의 뻘짓이 이제 끝났군요
감사합니드아..
