### ISSUE TITLE
서버 구동

### ISSUE THREAD

**Issue by jini5012** [monun/psychics#61]
debug.sh를 어떻게 쓰는 건가요?

**Comment by jini5012** [comment]
그거로 서버를 연다던데?

**Comment by patrick-choe** [comment]
디버그 서버는 일반적으로 사용할 필요가 없습니다.
psychics 개발 목적으로 사용되는 파일이며, 일반적인 사용자 분들은 평범하게 서버를 열고 플러그인 적용시켜주시면 됩니다.
