### ISSUE TITLE
빌드 중 오류

### ISSUE THREAD

**Issue by 21020183** [monun/psychics#66]
파일을 열었는데 
> Task :prepareKotlinBuildScriptModel UP-TO-DATE
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.github.monun:kommand-api:2.6.6
Could not resolve: io.github.monun:invfx-api:3.0.1
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.github.monun:kommand-api:2.6.6
Could not resolve: io.github.monun:invfx-api:3.0.1
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9
Could not resolve: io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT
Could not resolve: io.github.monun:tap-api:4.1.9

라고 뜨는데 어떻게 해야 하나요?

**Comment by qogusdn1017** [comment]
버그아닙니다. Java 16으로 업그레이드 후 다시 시도해보세요.

**ISSUE 템플릿 양식에 맞춰서 작성해주시면 문제 해결에 도움이 됩니다.**

문제 해결되셨다면 이슈 닫아주세요.
