### ISSUE TITLE
괴상한 클레스 로딩 (ability written with Scala)

### ISSUE THREAD

**Issue by muqhc** [monun/psychics#67]
**Describe the bug (어떤 버그인가요?)**
- 클레스를 이미 다 로드 했는데 괴상한 이름으로 또 로딩 시도 후 ClassNotFound를 토해버린다.

**To Reproduce (재현 과정)**
(동작을 재현하는 단계는 다음과 같습니다)
1. Scala 로 ability 를 작성합니다.
2. Gradle를 이용해서 빌드합니다. ( Gradle>pschics>psychics-abilities>ability-sample-scala>Tasks>build>build )
3. 해당 ability를 paper 서버에서 로딩시킵니다.

**Expected behavior (예상한 동작)**
(예상했던 일에 대해 명확하고 간결하게 써주세요.)

- 다른 ability 들과과 같이, 문제 없이 로딩됨을 예상했습니다.

**Screenshots (스크린샷)**
(가능하면, 스크린샷을 올려서 이해하기 쉽게 해 주세요.)
![제목 없음](https://user-images.githubusercontent.com/88622655/134670472-a83b406a-f8b9-4d98-be13-34992eeed610.png)

**Environment (개발 환경)**
- OS : Windows 10
- JDK version : openjdk 16.0.2
- Scala SDK version : 2.12.14
- Minecraft version : paper-1.17.1-276

**Source Code(소스 코드)**
Please write the source code you tried to execute (it also includes yml and kts files).
(실행하려고 한 소스 코드를 써 주세요. yml과 kts 파일도 포함됩니다.)
- https://github.com/muqhc/psychics/tree/SupportScala/psychics-abilities/ability-sample-scala/src/main

**Additional context(추가 설명)**
(추가 설명할 게 있다면 써 주세요!)
- 해당 ability는 Scala 작성을 위한 샘플이며 기존 ability-sample과 기능이 같습니다.
- (+ 해당 ability는 Scala로 작성되었습니다. )

**Comment by godlegendshot** [comment]
아마 이것 때문인 것 같은 #35를 한 번 확인해주세요
