### ISSUE TITLE
yml을 어떻게 작성해야 능력이 적용되나요?

### ISSUE THREAD

**Issue by hamtomaru** [monun/psychics#71]
wiki에 있는대로
abilities:
sample:
ability: ability-berserker-2.0.0-SNAPSHOT 
이렇게 작성했더니 계속
ability: .ability-berserker-2.0.0-SNAPSHOT
display-name: berserker
health-bonus: 0.0
health-regen-per-second: 0.0
mana: 0.0
mana-regen-per-second: 0.0
mana-color: BLUE
description:
- '{"italic":false,"color":"white","text":"설명"}'
abilities: {}
의 형태로 바뀌고 능력이 적용되지 않습니다. 작성을 메모장을 통해 했는데, 여기에 문제가 있던건가요? 

코틀린 v1.4.10
invFX v1.3.0
ProtocolLib v4.7.1-SNAPSHOT-b531
- JDK version : 16.0.2
- Minecraft version : 1.17.1
![image](https://user-images.githubusercontent.com/74965045/134765084-5832485e-8172-4a2f-a491-d8b58f8c091e.png)
위키대로 하고 ./psy reload 한 뒤 yml 파일
![image](https://user-images.githubusercontent.com/74965045/134765188-2b846902-4f56-440c-89d9-e831c541061b.png)
능력 적용 안됨

**Comment by kmj1809** [comment]
abilities:
  sample:
    ability: io.github.monun.berserker
들여쓰기랑 능력의 그룹을 써주셔야 합니다

**Comment by hamtomaru** [comment]
> abilities:
> sample:
> ability: io.github.monun.berserker
> 들여쓰기랑 능력의 그룹을 써주셔야 합니다

해결했습니당!
