### ISSUE TITLE
플러그인 빌드 오류

### ISSUE THREAD

**Issue by condblock** [monun/psychics#76]
빌드 하려고 ./gradlew build로 빌드했는데 빌드된 파일 안에 .mf파일밖에 없네요
자바16 사용중입니다
![Screenshot 2021-10-02 at 20 45 48](https://user-images.githubusercontent.com/72214833/135714689-cbbb375e-ba1b-4a5a-a9d4-a8361850c3bc.jpg)
![Screenshot 2021-10-02 at 20 43 17](https://user-images.githubusercontent.com/72214833/135715164-f7f426f6-7b77-4649-afdd-ce7bbf5b09f5.jpg)

**Comment by qogusdn1017** [comment]
버그아닙니다. build.gradle.kts 확인하면서 명령실행 부탁드립니디.

Issue 양식에 맞춰서 작성해주세요 제발

이슈닫아주세요

**Comment by heisenberg-cat** [comment]
이슈 닫아주세요

**Comment by heisenberg-cat** [comment]
이슈 닫아주세요
