### ISSUE TITLE
능력 랜덤 지급 커맨드

### ISSUE THREAD

**Issue by blugon09** [monun/psychics#83]
를 추가하려고하는데 모든 능력을 List로 불러오는 방법이 있나요?

**Comment by dolphin2410** [comment]
`PhysicsPlugin` 객체에 있는 `psychicManager`을 얻고, `psychicManager`의 `psychicConceptsByName`을 사용하면됩니다

**Comment by blugon09** [comment]
> `PhysicsPlugin` 객체에 있는 `psychicManager`을 얻고, `psychicManager`의 `psychicConceptsByName`을 사용하시면 될 것 같습니다

감사합니다

**Comment by heisenberg-cat** [comment]
이슈 닫아주세요
