### ISSUE TITLE
처음 클론을 생성하면 이런 오류가 나옵니다

### ISSUE THREAD

**Issue by maoo0676** [monun/psychics#84]
처음 클론을 생성하면 이런 오류가 나옵니다
![psychics-abilities 2021-11-12 오후 10_15_34](https://user-images.githubusercontent.com/92213805/141473885-a5abae0a-6110-4e94-8102-475f718c56e3.png)

**Comment by dolphin2410** [comment]
최신 버전으로 클론해 보세요
