### ISSUE TITLE
최신 클론 libs에 이상하게 나옵니다.

### ISSUE THREAD

**Issue by maoo0676** [monun/psychics#85]
최신 클론 libs에 이상하게 나옵니다.
또한 1.0.1버전에 적용이 안됩니다.
![psychics 2021-11-18 오후 10_57_12](https://user-images.githubusercontent.com/92213805/142429250-0d5dd5a0-47a2-4b6a-bf4b-1f32773e4a49.png)
[psychics\psychics-abilities\ability-vampire\build\libs에 파일 처럼 나옵니다.]

**Comment by dytroInc** [comment]
`psychics-abilities > Tasks > other > paperJar` 로 능력들을 빌드해보고 `psychics-core > Tasks > other > paperJar` 로 플러그인 자체를 빌드해보실 수 있나요?

능력자 플러그인 버전 1.0.1은 현재 깃허브에서 개발 진행되고 있는 능력자 구조랑 달라서 적용이 안 됩니다.
현재 능력자 구조를 사용하고 싶다면, 직접 플러그인을 빌드해서 사용하실 수 있습니다.

**Comment by maoo0676** [comment]
감사합니다 이슈 닫겠습니다
