### ISSUE TITLE
플러그인의 빌드가 되지 않습니다

### ISSUE THREAD

**Issue by JeonDohyeon** [monun/psychics#91]
### Prieror to look deeply through this issue(이슈를 들여다보기 전에)
:kr: 뒤에는 한글, :us: 뒤에는 영문이 적혀있습니다. 이 때문에 다른 이슈보다 길이가 길 수 있습니다.
(Korean after :kr:, english after :us:. Because of this, this issue could be longer than others.)
템플릿을 일부 수정했습니다. 볼드체(`**text**`)를 이용하면서 가독성을 높이기 위한 조치이니 양해 바랍니다.
(I edited template a little. It's to make it finer to read with using bold(`**text**`). Please consider about it.)

### Describe the bug (어떤 버그인가요?)
:kr:
플러그인의 빌드를 시도하면, `Caused by: java.lang.AssertionError: symbolic reference class is not accessible: class sun.nio.ch.FileChannelImpl, from class org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil (unnamed module @8e24743)`가 표시되며 빌드되지 않습니다.
core jar도 비정상적으로 작고, abilities zip은 1KB로 잡힙니다.(사실상 빈 파일)

:us:
When try to build plugin, it does not successfully build with showing: `Caused by: java.lang.AssertionError: symbolic reference class is not accessible: class sun.nio.ch.FileChannelImpl, from class org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil (unnamed module @8e24743)`.
Core JAR is irregularly small, and abilities.zip shows as 1KB(Actually an empty file).

### To Reproduce (재현 과정)
:kr:
1. 개발 환경을 만듭니다. Gradle과 Maven 등 InteliJ에서 사용하는 모든 참조가 없는 깨끗한 환경이어야 합니다.
2. Wiki에 나오는 대로, 순서를 지켜 Git에서 소스를 가져옵니다.
3. 터미널에서 bash는 `./gradlew build`, PowerShell은 `.\gradlew build`, CMD는 `gradlew build`를 실행합니다.
(GitHub에서 소스코드를 다운로드받아 바로 `gradlew build`를 쓰는 분은 없겠지만, 그렇게 하셔도 발생합니다.)
4. 나오는 오류 메시지를 확인합니다.(빌드 자체는 `Successful`(성공)로 잡힙니다.)

:us:
1. Create the clean environment. It should be a clean one with nothing InteliJ uses to build.
2. As the wiki shows, bring the source from Git.
3. Launch `./gradlew build` on bash, `.\gradlew build` on PowerShell, `gradlew build` on CMD.
(There'll be no one who just downloads archive from GitHub and immediately run `gradlew build`, but that also reproduces.)
4. Check out the error message.(It will show the build IS `Successful`.)

### Expected behavior (예상한 동작)
:kr: 아무런 오류 문구도 없이 빌드에 성공합니다. `abilities.zip`의 용량이 정상적으로 표시됩니다.
:us: Without any errors, it just successes to build. Archive `abilities.zip`'s file size seems to be normal.

### Screenshots (스크린샷)
Descriptions in :us:, Screenshots in :kr:
#### Screenshot 1: Build on InteliJ
![image](https://user-images.githubusercontent.com/34373595/150153947-b23a29cd-565f-46c6-a243-5288e89900da.png)
#### Screenshot 2: InteliJ Run/Debug Configuration(since I used those to run with one-click)
![image](https://user-images.githubusercontent.com/34373595/150154215-1f71b3b6-28e1-4ec7-8b80-aacfd3b0409c.png)
#### Screenshot 3: InteliJ Project Structure(JVM)
![image](https://user-images.githubusercontent.com/34373595/150154361-b4ded284-40c8-40f5-b9c6-cee39044eb87.png)

### Environment (개발 환경)
- OS : Windows 11 Home
- JDK version : Oracle Java JDK 17.0.1 (Also in SC3)
- Minecraft version : N/A(Not Server Client Bug: Build Failed)
(Targeted to: Minecraft 1.16.5 - Arclight Forge Hybrid / Not tested because of bad archive)

### Source Code(소스 코드)
**[Repository of Latest Commit until Build](https://github.com/JeonDohyeon/psychics-1/tree/5f22be8198b0a994faaa0c915d837e4f13987f26)**

### Additional context(추가 설명)
:kr: only
사실 새로 추가한 Listener(`org.bukkit.event.player.PlayerSwapHandItemsEvent` 사용) 때문인가 싶었는데, `psychics-core:compile-kotlin`과 소스에 같이 있는 기존 `psychics-abilities:*`에서도 동일한/유사한 오류가 나서 '일단 얘 문제는 아니구나' 싶었습니다. 혹시나 해당 코드에 문제가 있다면 그거에 대해서도 말씀해 주세요.

gradlew build에 대한 로그 파일 추가로 첨부합니다.
[BuildLog_InteliJ.txt](https://github.com/monun/psychics/files/7898100/BuildLog_InteliJ.txt)

**Comment by JeonDohyeon** [comment]
[plugin_core.zip](https://github.com/monun/psychics/files/7898233/psychics-core-2.0.0-SNAPSHOT.jar.zip)
[abilities.zip](https://github.com/monun/psychics/files/7898238/abilities.zip)
빌드된 아카이브 추가로 첨부합니다. Core의 경우 뜯어보니 정상적으로 빌드된 것처럼도 보입니다만, abilities의 경우 JAR에 `MANIFEST.MF`만 존재합니다.

**Comment by myoun** [comment]
gradle paperJar로 빌드 부탁드립니다.
[psychics/build.gradle.kts](https://github.com/monun/psychics/blob/master/psychics-abilities/build.gradle.kts#L29)

**Comment by JeonDohyeon** [comment]
> gradle paperJar로 빌드 부탁드립니다.
> [psychics/build.gradle.kts](https://github.com/monun/psychics/blob/master/psychics-abilities/build.gradle.kts#L29)

말씀해 주신 대로 빌드하니 잘 돌아가는 것 같습니다. 이슈 닫겠습니다.
